export LC_ALL="C"
export FOX_VERSION="R12.1"
export FOX_BUILD_TYPE="Unofficial"
export FOX_BUILD_DEVICE="rosemary"
export OF_AB_DEVICE=1
export OF_FORCE_USE_RECOVERY_FSTAB=1
export OF_USE_MAGISKBOOT=1
export OF_USE_MAGISKBOOT_FOR_ALL_PATCHES=1
export OF_SKIP_MULTIUSER_FOLDERS_BACKUP=1
export OF_DONT_PATCH_ENCRYPTED_DEVICE=1
export FOX_DELETE_AROMAFM=1

add_lunch_combo twrp_rosemary-eng
